import { Metadata } from "next";
import { Shield } from "lucide-react";
import Navbar from "@/components/landing/Navbar";
import Footer from "@/components/landing/Footer";
import Grid from "@/components/landing/ui/Grid";
import Separator from "@/components/landing/ui/Separator";

export const metadata: Metadata = {
  title: "Privacy Policy | Formix",
  description: "How we handle, protect, and process your data at Formix.",
};

export default function PrivacyPolicyPage() {
  return (
    <div className="min-h-screen bg-[#0a0a0a] flex flex-col relative selection:bg-neutral-800 selection:text-white">
      <Grid />
      <Navbar />

      <main className="flex-1 flex flex-col items-center relative z-10 w-full pt-20 pb-0">
        <div className="w-full max-w-300 flex flex-col border-x border-neutral-700/30 bg-[#0a0a0a] min-h-[calc(100vh-80px)]">
          {/* Header */}
          <div className="px-6 md:px-10 lg:px-24 py-16 lg:py-24 border-b border-neutral-700/30 text-left flex flex-col items-start animate-in fade-in slide-in-from-bottom-4 duration-700">
            <div className="flex items-center gap-3 mb-5 border border-white/10 w-max px-3 py-1 rounded-full bg-white/5">
              <Shield size={14} className="text-neutral-400" />
              <span className="text-[10px] font-mono uppercase tracking-widest text-neutral-300">
                Legal
              </span>
            </div>
            <h1 className="text-3xl md:text-5xl font-medium text-white mb-6 tracking-tight">
              Privacy Policy
            </h1>
            <p className="text-neutral-400 text-sm md:text-base font-mono">
              Last updated: April 28, 2026
            </p>
          </div>

          {/* Content */}
          <article className="px-6 md:px-10 lg:px-24 py-16 w-full max-w-4xl prose prose-invert prose-neutral lg:prose-lg prose-headings:font-medium prose-a:text-amber-400 hover:prose-a:text-amber-300 animate-in fade-in duration-1000 delay-150 fill-mode-both">
            <p>
              At Formix, we take your privacy seriously. This Privacy Policy
              explains how we collect, use, disclose, and safeguard your
              information when you visit our website or use our headless form
              infrastructure services.
            </p>

            <h2>1. Information We Collect</h2>
            <p>
              <strong>Account Data:</strong> When you register, we collect your
              name, email address, and authentication credentials (managed
              securely via BetterAuth).
              <br />
              <strong>Form Data:</strong> We process and store the data
              submitted through the APIs generated by Formix. As a
              infrastructure provider, we act as a data processor for the
              information your end-users submit.
              <br />
              <strong>Integration Data:</strong> To provide features like
              WhatsApp Flows or Slack notifications, we store necessary OAuth
              tokens and Webhook URLs. These are encrypted at rest using
              AES-256-GCM.
            </p>

            <h2>2. How We Use Your Information</h2>
            <ul>
              <li>
                To provide, operate, and maintain our headless API services.
              </li>
              <li>
                To process form submissions and route them to your configured
                integrations.
              </li>
              <li>
                To send administrative emails, security alerts, and product
                updates (if opted-in).
              </li>
              <li>
                To prevent fraudulent transactions, spam, and unauthorized
                access using rate limiting.
              </li>
            </ul>

            <h2>3. AI Processing</h2>
            <p>
              Formix uses Groq AI to generate JSON schemas from your prompts.{" "}
              <strong>
                We do not use your end-user submission data to train any AI
                models.
              </strong>{" "}
              Only the prompts you explicitly provide in the dashboard are sent
              to the AI engine for the purpose of schema generation.
            </p>

            <h2>4. Data Security</h2>
            <p>
              We implement industry-standard security measures, including HTTPS
              encryption in transit and AES-256 encryption at rest for sensitive
              credentials. Our database infrastructure is securely managed via
              Neon Postgres. However, no electronic transmission over the
              Internet can be guaranteed to be 100% secure.
            </p>

            <h2>5. Contact Us</h2>
            <p>
              If you have questions or comments about this Privacy Policy,
              please contact us at: <br />
              <a href="mailto:support@formix.com">support@formix.com</a>
            </p>
          </article>
        </div>

        {/* Separator */}
        <div className="w-full flex flex-col items-center relative z-10 bg-[#0a0a0a]">
          <div className="w-full h-px bg-neutral-700/30"></div>
          <div className="w-full max-w-300">
            <Separator />
          </div>
          <div className="w-full h-px bg-neutral-700/30"></div>
        </div>
      </main>

      <Footer />
    </div>
  );
}
